name: Update GitHub Pages
run-name: Rebuild Jupyter book and upload to GitHub pages 📖
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master

    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        publish_dir: programming_notes/_build/html/