name: "Update GitHub Pages"
run-name: Rebuild book and upload to GH pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "programming_notes/"
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: programming_notes/_build/html/