name: "Update GitHub Pages"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: programming_notes/_build/html/